//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtsuMoriFatCook.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Setting : global::System.Configuration.ApplicationSettingsBase {
        
        private static Setting defaultInstance = ((Setting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Setting())));
        
        public static Setting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int オーガニックパン {
            get {
                return ((int)(this["オーガニックパン"]));
            }
            set {
                this["オーガニックパン"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int かしパン {
            get {
                return ((int)(this["かしパン"]));
            }
            set {
                this["かしパン"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int カボチャのスープ {
            get {
                return ((int)(this["カボチャのスープ"]));
            }
            set {
                this["カボチャのスープ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int カボチャのニョッキ {
            get {
                return ((int)(this["カボチャのニョッキ"]));
            }
            set {
                this["カボチャのニョッキ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int カボチャのベーグルサンド {
            get {
                return ((int)(this["カボチャのベーグルサンド"]));
            }
            set {
                this["カボチャのベーグルサンド"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int キャロットラペ {
            get {
                return ((int)(this["キャロットラペ"]));
            }
            set {
                this["キャロットラペ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int グラタン {
            get {
                return ((int)(this["グラタン"]));
            }
            set {
                this["グラタン"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int こくとう {
            get {
                return ((int)(this["こくとう"]));
            }
            set {
                this["こくとう"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ココナッツオイル {
            get {
                return ((int)(this["ココナッツオイル"]));
            }
            set {
                this["ココナッツオイル"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int サラダ {
            get {
                return ((int)(this["サラダ"]));
            }
            set {
                this["サラダ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ジャガイモのカレー {
            get {
                return ((int)(this["ジャガイモのカレー"]));
            }
            set {
                this["ジャガイモのカレー"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ジャガイモのガレット {
            get {
                return ((int)(this["ジャガイモのガレット"]));
            }
            set {
                this["ジャガイモのガレット"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ジャガイモのニョッキ {
            get {
                return ((int)(this["ジャガイモのニョッキ"]));
            }
            set {
                this["ジャガイモのニョッキ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ジャガイモのポタージュ {
            get {
                return ((int)(this["ジャガイモのポタージュ"]));
            }
            set {
                this["ジャガイモのポタージュ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int じゃがバター {
            get {
                return ((int)(this["じゃがバター"]));
            }
            set {
                this["じゃがバター"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int そうざいパン {
            get {
                return ((int)(this["そうざいパン"]));
            }
            set {
                this["そうざいパン"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int チェリージャム {
            get {
                return ((int)(this["チェリージャム"]));
            }
            set {
                this["チェリージャム"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ちぎりパン {
            get {
                return ((int)(this["ちぎりパン"]));
            }
            set {
                this["ちぎりパン"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int トマトカレー {
            get {
                return ((int)(this["トマトカレー"]));
            }
            set {
                this["トマトカレー"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int トマトソースパスタ {
            get {
                return ((int)(this["トマトソースパスタ"]));
            }
            set {
                this["トマトソースパスタ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int トマトのアヒージョ {
            get {
                return ((int)(this["トマトのアヒージョ"]));
            }
            set {
                this["トマトのアヒージョ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int トマトのベーグルサンド {
            get {
                return ((int)(this["トマトのベーグルサンド"]));
            }
            set {
                this["トマトのベーグルサンド"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ナシのジャム {
            get {
                return ((int)(this["ナシのジャム"]));
            }
            set {
                this["ナシのジャム"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ナポリタンスパゲッティ {
            get {
                return ((int)(this["ナポリタンスパゲッティ"]));
            }
            set {
                this["ナポリタンスパゲッティ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ニンジンのニョッキ {
            get {
                return ((int)(this["ニンジンのニョッキ"]));
            }
            set {
                this["ニンジンのニョッキ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ニンジンのはっぱカレー {
            get {
                return ((int)(this["ニンジンのはっぱカレー"]));
            }
            set {
                this["ニンジンのはっぱカレー"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ニンジンのベーグルサンド {
            get {
                return ((int)(this["ニンジンのベーグルサンド"]));
            }
            set {
                this["ニンジンのベーグルサンド"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ニンジンのポタージュ {
            get {
                return ((int)(this["ニンジンのポタージュ"]));
            }
            set {
                this["ニンジンのポタージュ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int パン {
            get {
                return ((int)(this["パン"]));
            }
            set {
                this["パン"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int パングラタン {
            get {
                return ((int)(this["パングラタン"]));
            }
            set {
                this["パングラタン"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int パンプキンカレー {
            get {
                return ((int)(this["パンプキンカレー"]));
            }
            set {
                this["パンプキンカレー"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int パンプキンパイ {
            get {
                return ((int)(this["パンプキンパイ"]));
            }
            set {
                this["パンプキンパイ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ピーチジャム {
            get {
                return ((int)(this["ピーチジャム"]));
            }
            set {
                this["ピーチジャム"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int フィッシュアンドチップス {
            get {
                return ((int)(this["フィッシュアンドチップス"]));
            }
            set {
                this["フィッシュアンドチップス"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int フライドポテト {
            get {
                return ((int)(this["フライドポテト"]));
            }
            set {
                this["フライドポテト"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int フルーツサラダ {
            get {
                return ((int)(this["フルーツサラダ"]));
            }
            set {
                this["フルーツサラダ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int フルーツサンド {
            get {
                return ((int)(this["フルーツサンド"]));
            }
            set {
                this["フルーツサンド"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int フルーツのベーグルサンド {
            get {
                return ((int)(this["フルーツのベーグルサンド"]));
            }
            set {
                this["フルーツのベーグルサンド"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int フルーツピザ {
            get {
                return ((int)(this["フルーツピザ"]));
            }
            set {
                this["フルーツピザ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ベジタブルクレープ {
            get {
                return ((int)(this["ベジタブルクレープ"]));
            }
            set {
                this["ベジタブルクレープ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ベジタブルサンド {
            get {
                return ((int)(this["ベジタブルサンド"]));
            }
            set {
                this["ベジタブルサンド"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int マーマレード {
            get {
                return ((int)(this["マーマレード"]));
            }
            set {
                this["マーマレード"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int マルゲリータ {
            get {
                return ((int)(this["マルゲリータ"]));
            }
            set {
                this["マルゲリータ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int まるごとトマトのサラダ {
            get {
                return ((int)(this["まるごとトマトのサラダ"]));
            }
            set {
                this["まるごとトマトのサラダ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ミネストローネ {
            get {
                return ((int)(this["ミネストローネ"]));
            }
            set {
                this["ミネストローネ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int やさいのキッシュ {
            get {
                return ((int)(this["やさいのキッシュ"]));
            }
            set {
                this["やさいのキッシュ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int やさいのピクルス {
            get {
                return ((int)(this["やさいのピクルス"]));
            }
            set {
                this["やさいのピクルス"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int リンゴジャム {
            get {
                return ((int)(this["リンゴジャム"]));
            }
            set {
                this["リンゴジャム"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int アイシングクッキー {
            get {
                return ((int)(this["アイシングクッキー"]));
            }
            set {
                this["アイシングクッキー"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int アイシングプレッツェル {
            get {
                return ((int)(this["アイシングプレッツェル"]));
            }
            set {
                this["アイシングプレッツェル"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int アップルゼリー {
            get {
                return ((int)(this["アップルゼリー"]));
            }
            set {
                this["アップルゼリー"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int アップルパイ {
            get {
                return ((int)(this["アップルパイ"]));
            }
            set {
                this["アップルパイ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int オレンジスムージー {
            get {
                return ((int)(this["オレンジスムージー"]));
            }
            set {
                this["オレンジスムージー"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int オレンジゼリー {
            get {
                return ((int)(this["オレンジゼリー"]));
            }
            set {
                this["オレンジゼリー"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int オレンジタルト {
            get {
                return ((int)(this["オレンジタルト"]));
            }
            set {
                this["オレンジタルト"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int オレンジパイ {
            get {
                return ((int)(this["オレンジパイ"]));
            }
            set {
                this["オレンジパイ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int オレンジパウンドケーキ {
            get {
                return ((int)(this["オレンジパウンドケーキ"]));
            }
            set {
                this["オレンジパウンドケーキ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int カボチャのカップケーキ {
            get {
                return ((int)(this["カボチャのカップケーキ"]));
            }
            set {
                this["カボチャのカップケーキ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int カボチャのスコーン {
            get {
                return ((int)(this["カボチャのスコーン"]));
            }
            set {
                this["カボチャのスコーン"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int カボチャのパウンドケーキ {
            get {
                return ((int)(this["カボチャのパウンドケーキ"]));
            }
            set {
                this["カボチャのパウンドケーキ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int キャロットケーキ {
            get {
                return ((int)(this["キャロットケーキ"]));
            }
            set {
                this["キャロットケーキ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int キャロットジュース {
            get {
                return ((int)(this["キャロットジュース"]));
            }
            set {
                this["キャロットジュース"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int キャロットスコーン {
            get {
                return ((int)(this["キャロットスコーン"]));
            }
            set {
                this["キャロットスコーン"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int クッキー {
            get {
                return ((int)(this["クッキー"]));
            }
            set {
                this["クッキー"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ケークサレ {
            get {
                return ((int)(this["ケークサレ"]));
            }
            set {
                this["ケークサレ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int こくとうカップケーキ {
            get {
                return ((int)(this["こくとうカップケーキ"]));
            }
            set {
                this["こくとうカップケーキ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int こくとうパウンドケーキ {
            get {
                return ((int)(this["こくとうパウンドケーキ"]));
            }
            set {
                this["こくとうパウンドケーキ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ココナッツクッキー {
            get {
                return ((int)(this["ココナッツクッキー"]));
            }
            set {
                this["ココナッツクッキー"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ココナッツのパンケーキ {
            get {
                return ((int)(this["ココナッツのパンケーキ"]));
            }
            set {
                this["ココナッツのパンケーキ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ココナッツプリン {
            get {
                return ((int)(this["ココナッツプリン"]));
            }
            set {
                this["ココナッツプリン"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ココナッツミルク {
            get {
                return ((int)(this["ココナッツミルク"]));
            }
            set {
                this["ココナッツミルク"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int さくらんぼスムージー {
            get {
                return ((int)(this["さくらんぼスムージー"]));
            }
            set {
                this["さくらんぼスムージー"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int さくらんぼゼリー {
            get {
                return ((int)(this["さくらんぼゼリー"]));
            }
            set {
                this["さくらんぼゼリー"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ジャムクッキー {
            get {
                return ((int)(this["ジャムクッキー"]));
            }
            set {
                this["ジャムクッキー"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int シュガークレープ {
            get {
                return ((int)(this["シュガークレープ"]));
            }
            set {
                this["シュガークレープ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int スコーン {
            get {
                return ((int)(this["スコーン"]));
            }
            set {
                this["スコーン"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int チェリータルト {
            get {
                return ((int)(this["チェリータルト"]));
            }
            set {
                this["チェリータルト"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int チェリーパイ {
            get {
                return ((int)(this["チェリーパイ"]));
            }
            set {
                this["チェリーパイ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int トマトジュース {
            get {
                return ((int)(this["トマトジュース"]));
            }
            set {
                this["トマトジュース"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ナシスムージー {
            get {
                return ((int)(this["ナシスムージー"]));
            }
            set {
                this["ナシスムージー"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ナシのゼリー {
            get {
                return ((int)(this["ナシのゼリー"]));
            }
            set {
                this["ナシのゼリー"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ナシのタルト {
            get {
                return ((int)(this["ナシのタルト"]));
            }
            set {
                this["ナシのタルト"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ナシのパイ {
            get {
                return ((int)(this["ナシのパイ"]));
            }
            set {
                this["ナシのパイ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int パウンドケーキ {
            get {
                return ((int)(this["パウンドケーキ"]));
            }
            set {
                this["パウンドケーキ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ハトのすサブレ {
            get {
                return ((int)(this["ハトのすサブレ"]));
            }
            set {
                this["ハトのすサブレ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ハロウィンなクッキー {
            get {
                return ((int)(this["ハロウィンなクッキー"]));
            }
            set {
                this["ハロウィンなクッキー"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int パンケーキ {
            get {
                return ((int)(this["パンケーキ"]));
            }
            set {
                this["パンケーキ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ピーチゼリー {
            get {
                return ((int)(this["ピーチゼリー"]));
            }
            set {
                this["ピーチゼリー"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ピーチタルト {
            get {
                return ((int)(this["ピーチタルト"]));
            }
            set {
                this["ピーチタルト"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ピーチパイ {
            get {
                return ((int)(this["ピーチパイ"]));
            }
            set {
                this["ピーチパイ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int フルーツカップケーキ {
            get {
                return ((int)(this["フルーツカップケーキ"]));
            }
            set {
                this["フルーツカップケーキ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int フルーツクレープ {
            get {
                return ((int)(this["フルーツクレープ"]));
            }
            set {
                this["フルーツクレープ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int フルーツタルト {
            get {
                return ((int)(this["フルーツタルト"]));
            }
            set {
                this["フルーツタルト"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int フルーツのスコーン {
            get {
                return ((int)(this["フルーツのスコーン"]));
            }
            set {
                this["フルーツのスコーン"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int フルーツのパンケーキ {
            get {
                return ((int)(this["フルーツのパンケーキ"]));
            }
            set {
                this["フルーツのパンケーキ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int フルーツのパイ {
            get {
                return ((int)(this["フルーツのパイ"]));
            }
            set {
                this["フルーツのパイ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int プレーンカップケーキ {
            get {
                return ((int)(this["プレーンカップケーキ"]));
            }
            set {
                this["プレーンカップケーキ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int プレッツェル {
            get {
                return ((int)(this["プレッツェル"]));
            }
            set {
                this["プレッツェル"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int モモスムージー {
            get {
                return ((int)(this["モモスムージー"]));
            }
            set {
                this["モモスムージー"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int やさいクッキー {
            get {
                return ((int)(this["やさいクッキー"]));
            }
            set {
                this["やさいクッキー"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int やさいのカップケーキ {
            get {
                return ((int)(this["やさいのカップケーキ"]));
            }
            set {
                this["やさいのカップケーキ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int リンゴスムージー {
            get {
                return ((int)(this["リンゴスムージー"]));
            }
            set {
                this["リンゴスムージー"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int リンゴのタルト {
            get {
                return ((int)(this["リンゴのタルト"]));
            }
            set {
                this["リンゴのタルト"] = value;
            }
        }
    }
}
